# Generated by Django 5.2.12 on 2026-04-09 02:53

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alojamiento',
            options={'verbose_name': 'Alojamiento', 'verbose_name_plural': 'Alojamientos'},
        ),
        migrations.AlterModelOptions(
            name='anfitrion',
            options={'verbose_name': 'Anfitrión', 'verbose_name_plural': 'Anfitriones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos/', verbose_name='Imagen del lugar'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='capacidad_personas',
            field=models.IntegerField(verbose_name='Capacidad (personas)'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del alojamiento'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='precio_por_noche',
            field=models.IntegerField(verbose_name='Precio por noche'),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='idiomas',
            field=models.CharField(max_length=100, verbose_name='Idiomas que habla'),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_huespedes',
            field=models.IntegerField(default=1, verbose_name='Cantidad de huéspedes'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre_viajero',
            field=models.CharField(max_length=100, verbose_name='Nombre del viajero'),
        ),
    ]
