# Generated by Django 5.2.12 on 2026-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_alojamiento_options_alter_anfitrion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='disponibilidad',
            field=models.DateField(blank=True, null=True, verbose_name='Disponibilidad'),
        ),
    ]
