# Generated by Django 5.2.12 on 2026-04-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alojamiento_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='disponibilidad',
        ),
    ]
