# Generated by Django 5.2.12 on 2026-04-10 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_remove_alojamiento_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='anfitrion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alojamientos', to=settings.AUTH_USER_MODEL, verbose_name='Anfitrión'),
            preserve_default=False,
        ),
    ]
