# Generated by Django 5.2.12 on 2026-04-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alojamiento_anfitrion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_viajero',
        ),
        migrations.AddField(
            model_name='reserva',
            name='alojamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mi_app.alojamiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje para el anfitrión'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_reservas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
